//AUTOGENERATED FILE FROM png2mtspr
#define detective_platform_stand_TILE_H 16
#define detective_platform_stand_WIDTH 24
#define detective_platform_stand_HEIGHT 32
#define detective_platform_stand_PIVOT_X 12
#define detective_platform_stand_PIVOT_Y 16

extern const UINT8 detective_platform_stand_data[192];
extern const metasprite_t* const detective_platform_stand_metasprites[1];
