//AUTOGENERATED FILE FROM png2mtspr
#define detective_large_TILE_H 16
#define detective_large_WIDTH 24
#define detective_large_HEIGHT 32
#define detective_large_PIVOT_X 12
#define detective_large_PIVOT_Y 16

extern const UINT8 detective_large_data[2112];
extern const metasprite_t* const detective_large_metasprites[17];
