//AUTOGENERATED FILE FROM png2mtspr
#define detective_large_walk_TILE_H 16
#define detective_large_walk_WIDTH 24
#define detective_large_walk_HEIGHT 32
#define detective_large_walk_PIVOT_X 12
#define detective_large_walk_PIVOT_Y 16

extern const UINT8 detective_large_walk_data[704];
extern const metasprite_t* const detective_large_walk_metasprites[6];
